config/routes.rb
Rails.application.routes.draw do

  resources :information
  resources :teams
  resources :members
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
   match '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
   unauthenticated :user do
     root to: 'login#index', as: nil
   end
  end

  root to: "home#index"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

end

app/models/information.rb
class Information < ActiveRecord::Base

  enum info_type: [:news, :important, :casual]

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  layout "information"
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:purpose, :idea, :info_type, :responsible, :description)
    end

end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.haml
= form_for @information, :html => { :class => "form-horizontal information" } do |f|
  - if @information.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@information.errors.count, "error")
          prohibited this information from being saved:
      .panel-body
        %ul
          - @information.errors.full_messages.each do |msg|
            %li= msg
  .control-group.col-lg-6
    = f.label :purpose, :class => 'control-label'
    .controls
      = f.text_field :purpose, :class => 'form-control'
    = error_span(@information[:purpose])
  .control-group.col-lg-6
    = f.label :responsible, :class => 'control-label'
    .controls
      = f.text_field :responsible, :class => 'form-control'
    = error_span(@information[:responsible])
  .control-group.col-lg-6
    = f.label :idea, :class => 'control-label'
    .controls
      = f.text_area :idea, :class => 'form-control'
    = error_span(@information[:idea])
  .control-group.col-lg-6
    = f.label :info_type, :class => 'control-label'
    .controls
      = f.select :info_type, Information.info_types.map { |i| [i.first.humanize, i.first] }, :class => 'form-control'
    = error_span(@information[:type])
  .control-group.col-lg-6
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'form-control'
    = error_span(@information[:description])
  .btn-group.col-lg-12
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      information_index_path, :class => 'btn btn-default'          |

app/views/information/edit.html.haml
- model_class = Information
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/information/index.html.haml
- model_class = Information
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
  
  
  .col-lg-12.info-page
    - @information.each do |information|
      .col-lg-4
        = link_to information_path(information), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, class: "trash" do
          .glyphicon.glyphicon-trash

        %a.info{:href => edit_information_path(information)}
          %ul.well.nav.nav-list{ :class => information.try(:info_type) }
            %li.nav-header
              %b= information.purpose
            %li= information.idea
            %li
              %b= t(".responsible") 
              \:
              = information.responsible
  
    -# %tr
    -#   %td= link_to information.id, information_path(information)
    -#   %td= information.purpose
    -#   %td= information.idea
    -#   %td= information.responsible
    -#   %td= information.description
    -#   %td= l information.created_at
    -#   %td
    -#     = link_to t('.edit'), edit_information_path(information), :class => 'btn btn-default btn-xs'
    -#     = link_to t('.destroy'), information_path(information), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
      

= link_to t('.new'), new_information_path, :class => 'btn btn-primary'

app/views/information/new.html.haml
- model_class = Information
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/information/show.html.haml
- model_class = Information
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:purpose)
      \:
  %dd= @information.purpose
  %dt
    %strong
      = model_class.human_attribute_name(:idea)
      \:
  %dd= @information.idea
  %dt
    %strong
      = model_class.human_attribute_name(:info_type)
      \:
  %dd= @information.info_type.try(:humanize)
  %dt
    %strong
      = model_class.human_attribute_name(:responsible)
      \:
  %dd= @information.responsible
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @information.description
= link_to t('.back'), information_index_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_information_path(@information), :class => 'btn btn-default' 
= link_to t('.destroy', :default => t("helpers.links.destroy")), information_path(@information), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' 