config/routes.rb
Rails.application.routes.draw do

  resources :information
  resources :teams
  resources :members
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
   match '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
   unauthenticated :user do
     root to: 'login#index', as: nil
   end
  end

  root to: "home#index"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BridgePlatform"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", "models/#{params[:controller]}", :media => "all", 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", "models/#{params[:controller]}", 'data-turbolinks-track' => true

  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} 
          = image_tag("logo_32x32.png")
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to t(Member.model_name.human.pluralize.titleize), members_url if can? :read, Member
            %li= link_to t(Team.model_name.human.pluralize.titleize), teams_url if can? :read, Team
            %li= link_to t(Information.model_name.human.pluralize.titleize), information_index_url if can? :read, Information
            %li.right= link_to('Sair', destroy_user_session_path, method: :delete, class: "logout") unless current_user.nil?
    .container.content
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          - unless current_user.nil?
            .sidebar-nav
              %h3
                = t(".news")
              - Information.last(3).reverse.each do |info|
                %ul.well.nav.nav-list{ :class => info.try(:info_type) }
                  %li.nav-header
                    %b= info.purpose
                  %li= info.idea
                  %li
                    %b
                      = t(".responsible")
                      \:
                    = info.responsible
                  %li= link_to t(".more"), information_path(info), class: "btn col-md"
    %footer
      - if content_for?(:footer)
        .footer-content
          = yield(:footer)
      %p © A Ponte 2016

app/views/layouts/information.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BridgePlatform"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", "models/#{params[:controller]}", :media => "all", 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", "models/#{params[:controller]}", 'data-turbolinks-track' => true

  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"} 
          = image_tag("logo_32x32.png")
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to t(Member.model_name.human.pluralize.titleize), members_url if can? :read, Member
            %li= link_to t(Team.model_name.human.pluralize.titleize), teams_url if can? :read, Team
            %li= link_to t(Information.model_name.human.pluralize.titleize), information_index_url if can? :read, Information
            %li.right= link_to('Sair', destroy_user_session_path, method: :delete, class: "logout") unless current_user.nil?  
    .container.content
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
        
              
    %footer
      - if content_for?(:footer)
        .footer-content
          = yield(:footer)
      %p © A Ponte 2016

app/views/layouts/welcome.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BridgePlatform"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", "#{params[:controller]}", :media => "all", 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", "#{params[:controller]}", 'data-turbolinks-track' => true

  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"} 
          = image_tag("logo_32x32.png")
    .container.content
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .sidebar-nav
            %ul.well.nav.nav-list.news
              %li.nav-header
                %b Membros
              %li Nunca foi tão fácil gerenciar os dados dos membros com email, telefone, até qual bixinho de estimação ele maltrata.
            %ul.well.nav.nav-list.important  
              %li.nav-header
                %b Manutenção de notícias
              %li Nada de posto Ipiranga! Você do conexão nunca mais irá informar algo errado! 
            %ul.well.nav.nav-list.casual  
              %li.nav-header
                %b Visitantes
              %li Do que adianta anotar os dados do visitante se você não vai mandar o email mesmo? Deixa que nós fazemos isso por você! Envio automático!
              
              
    %footer
      - if content_for?(:footer)
        .footer-content
          = yield(:footer)
      %p © A Ponte 2016