config/routes.rb
Rails.application.routes.draw do

  resources :information
  resources :teams
  resources :members
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions]

  as :user do
   match '/users/logout' => 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
   unauthenticated :user do
     root to: 'login#index', as: nil
   end
  end

  root to: "home#index"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_and_belongs_to_many :teams
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource param_method: 'member_params'
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :birthdate, :address_name, :address_number, :address_complement, :address_zip_code, :observation, team_ids: [])
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= form_for @member, :html => { :class => "form-horizontal member" } do |f|
  - if @member.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@member.errors.count, "error")
          prohibited this member from being saved:
      .panel-body
        %ul
          - @member.errors.full_messages.each do |msg|
            %li= msg
  .control-group.col-lg-12
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control', required: true
    = error_span(@member[:name])
  .control-group.col-lg-12
    = f.label :birthdate, :class => 'control-label'
    .controls
      = f.date_field :birthdate, :class => 'form-control'
    = error_span(@member[:birhdate])
  .control-group.col-lg-8
    = f.label :address_name, :class => 'control-label'
    .controls
      = f.text_field :address_name, :class => 'form-control'
    = error_span(@member[:address_name])
  .control-group.col-lg-4
    = f.label :address_number, :class => 'control-label'
    .controls
      = f.number_field :address_number, :class => 'form-control'
    = error_span(@member[:address_number])
  .control-group.col-lg-8
    = f.label :address_complement, :class => 'control-label'
    .controls
      = f.text_field :address_complement, :class => 'form-control'
    = error_span(@member[:address_complement])
  .control-group.col-lg-4
    = f.label :address_zip_code, :class => 'control-label'
    .controls
      = f.text_field :address_zip_code, :class => 'form-control'
    = error_span(@member[:address_zip_code])
  .control-group.col-lg-12
    = f.label :teams, :class => 'control-label'
    .controls
      = f.select :team_ids, Team.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, style: "width: 100%"
    = error_span(@member[:teams])
  .control-group.col-lg-12
    = f.label :observation, :class => 'control-label'
    .controls
      = f.text_area :observation, :class => 'form-control'
    = error_span(@member[:observation])
  .btn-group.col-lg-12
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      members_path, :class => 'btn btn-default'                    |

app/views/members/edit.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/members/index.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:birthdate)
      %th= model_class.human_attribute_name(:observation)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.id, member_path(member)
        %td= member.name
        %td= member.birthdate
        %td= member.observation
        %td= l member.created_at
        %td
          = link_to t('.edit'), edit_member_path(member), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy'), member_path(member), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
= link_to t('.new', :default => t("helpers.links.new")), new_member_path, :class => 'btn btn-primary'

app/views/members/new.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/members/show.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @member.name
  %dt
    %strong
      = model_class.human_attribute_name(:address_name)
      \:
  %dd= @member.address_name
  %dt
    %strong
      = model_class.human_attribute_name(:address_number)
      \:
  %dd= @member.address_number
  %dt
    %strong
      = model_class.human_attribute_name(:address_complement)
      \:
  %dd= @member.address_complement
  %dt
    %strong
      = model_class.human_attribute_name(:address_zip_code)
      \:
  %dd= @member.address_zip_code
  %dt
    %strong
      = model_class.human_attribute_name(:birthdate)
      \:
  %dd= @member.birthdate
  %dt
    %strong
      = model_class.human_attribute_name(:teams)
      \:
  %dd= @member.teams.map { |t| t.name }.join ", "
  %dt
    %strong
      = model_class.human_attribute_name(:observation)
      \:
  %dd= @member.observation
= link_to t('.back'), members_path, :class => 'btn btn-default'
= link_to t('.edit'), edit_member_path(@member), :class => 'btn btn-default'
= link_to t('.destroy'), member_path(@member), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'